#!/bin/bash
sudo yum update -y
sudo yum install httpd -y
sudo systemctl start httpd
sudo systemctl enable httpd
echo "</h1>Welcome to the Avengers Headquater</h1>" | sudo tee /var/www/html/index.html
